import { PresetConfig, PresetKey } from '@/types';

export const CONTENT_PRESETS: Record<PresetKey, PresetConfig> = {
  animeAction: {
    key: 'animeAction',
    name: 'Anime Action',
    description: 'Prioritizes explosive combats, sword clashes, power transformations, fast camera moves, and impact moments.',
    icon: 'Swords',
    weights: {
      visualActivity: 0.25,
      actionScore: 0.35,
      audioEnergy: 0.15,
      speechScore: 0.05,
      facePresence: 0.05,
      sceneImportance: 0.05,
      hookStrength: 0.10,
    },
    defaultDuration: 30,
    prioritizeHook: true,
    minMotionThreshold: 0.35,
  },
  animeEmotional: {
    key: 'animeEmotional',
    name: 'Anime Emotional',
    description: 'Prioritizes character close-ups, emotional dialogue, dramatic pauses, tears, and orchestral music swells.',
    icon: 'HeartHandshake',
    weights: {
      visualActivity: 0.10,
      actionScore: 0.10,
      audioEnergy: 0.15,
      speechScore: 0.30,
      facePresence: 0.20,
      sceneImportance: 0.10,
      hookStrength: 0.05,
    },
    defaultDuration: 45,
    prioritizeHook: false,
    minMotionThreshold: 0.15,
  },
  animeHype: {
    key: 'animeHype',
    name: 'Anime Hype / AMV',
    description: 'High-energy fast cuts synced with bass drops, aura flares, and peak intensity battles for maximum adrenaline.',
    icon: 'Flame',
    weights: {
      visualActivity: 0.30,
      actionScore: 0.30,
      audioEnergy: 0.20,
      speechScore: 0.00,
      facePresence: 0.05,
      sceneImportance: 0.05,
      hookStrength: 0.10,
    },
    defaultDuration: 20,
    prioritizeHook: true,
    minMotionThreshold: 0.40,
  },
  dialogue: {
    key: 'dialogue',
    name: 'Dialogue Highlight',
    description: 'Focuses on speech clarity, critical lore reveals, monologue moments, and subtitled conversations.',
    icon: 'MessageSquareQuote',
    weights: {
      visualActivity: 0.05,
      actionScore: 0.05,
      audioEnergy: 0.10,
      speechScore: 0.45,
      facePresence: 0.20,
      sceneImportance: 0.10,
      hookStrength: 0.05,
    },
    defaultDuration: 30,
    prioritizeHook: true,
    minMotionThreshold: 0.10,
  },
  generalViral: {
    key: 'generalViral',
    name: 'General Viral',
    description: 'Balanced multi-signal detector for podcasts, gaming clutches, reaction moments, and all long-form videos.',
    icon: 'Sparkles',
    weights: {
      visualActivity: 0.20,
      actionScore: 0.25,
      audioEnergy: 0.15,
      speechScore: 0.15,
      facePresence: 0.10,
      sceneImportance: 0.05,
      hookStrength: 0.10,
    },
    defaultDuration: 30,
    prioritizeHook: true,
    minMotionThreshold: 0.25,
  },
};

export const DEFAULT_PRESET: PresetKey = 'animeAction';
